# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Azure Pipeline Template for invoking a published AML pipeline for execution

parameters:
- name: jobDisplayName
  type: string
- name: serviceConnection
  type: string
- name: resourceGroup
  type: string
- name: amlWorkspace
  type: string
- name: pipelineName
  type: string
- name: experimentName
  type: string
- name: dependsOn
  type: string
  default: []

jobs:

  - job: pipeline_id
    displayName: 'Get AML Pipeline ID'
    dependsOn: ${{parameters.dependsOn}}
    steps:
      # TODO: temporary fixed for bug in az cli 2.30 is corrected
      # Downgrade azure-devops 0.21.0 due to this error: https://github.com/microsoft/dstoolkit-mlops-base/issues/47
      - task: AzureCLI@1
        displayName: 'Downgrade azure-devops 0.21.0'
        inputs:
          azureSubscription: ${{parameters.serviceConnection}}
          scriptLocation: inlineScript
          inlineScript: |
            az extension remove --name azure-devops
            az extension add --name azure-devops --version 0.21.0

      # Downgrade az cli due to this error: https://github.com/microsoft/dstoolkit-mlops-base/issues/47
      - task: Bash@3
        displayName: "Bash: Downgrade AZ CLI to [2.29.2]"
        inputs:
          targetType: "inline"
          workingDirectory: "$(Build.SourcesDirectory)"
          script: |
            sudo add-apt-repository https://packages.microsoft.com/repos/azure-cli
            sudo apt update
            apt-cache policy azure-cli
            sudo apt install -y --allow-downgrades azure-cli=2.29.2-1~bionic

      - task: AzureCLI@1
        name: get_pipeline_id
        displayName: 'Get AML Pipeline ID'
        inputs:
          azureSubscription: ${{parameters.serviceConnection}}
          scriptLocation: inlineScript
          inlineScript: |
            # Install ML extension
            az extension add -n azure-cli-ml
            az extension list
            # Get pipeline ID
            workspace_params="--workspace-name ${{parameters.amlWorkspace}} --resource-group ${{parameters.resourceGroup}}"
            pipeline_id=$(az ml pipeline list $workspace_params --query "[?Name == '${{parameters.pipelineName}}'].Id" -o tsv)    
            if [ -n "$pipeline_id" ]; then
              echo "Found pipeline '${{parameters.pipelineName}}' with ID: $pipeline_id"
              echo "##vso[task.setvariable variable=pipeline_id;isOutput=true;]$pipeline_id"
            else
              echo "Pipeline '${{parameters.pipelineName}}' not found in workspace"
              exit 1
            fi

  - job: invoke_pipeline
    displayName: ${{parameters.jobDisplayName}}
    pool: server
    timeoutInMinutes: 0
    dependsOn: pipeline_id
    variables: 
      pipeline_id: $[ dependencies.pipeline_id.outputs['get_pipeline_id.pipeline_id'] ]
    steps:
        - task: ms-air-aiagility.vss-services-azureml.azureml-restApi-task.MLPublishedPipelineRestAPITask@0
          displayName: 'Invoke AML Pipeline'
          inputs:
            azureSubscription: '${{parameters.serviceConnection}}'
            PipelineId: '$(PIPELINE_ID)'
            ExperimentName: '${{parameters.experimentName}}'
